remote_theme: Breitband-Inc/cayman
domain: Breitband-Inc.github.io
url: https://Breitband-Inc.github.io/
title: Breitband Group
#description: IT and so much more
permalink: pretty
relative_links:
  enabled:     true
  collections: true
exclude:
  - README.md
