remote_theme: Breitband-Inc/cayman
domain: Breitband.group
url: https://Breitband.group/
title: BreitbaND Group
#description: IT and so much more
permalink: pretty
#lang: de-DE
lang: en-US
relative_links:
  enabled:     true
  collections: true
#exclude:
#  - README.md

theme: jekyll-theme-hacker