remote_theme: Breitband-Inc/cayman
domain: Breitband.group
url: https://Breitband.group/
title: BreitbaND Group
#description: IT and so much more
permalink: pretty
lang: 
  - de_DE
  - en_US
relative_links:
  enabled:     true
  collections: true
exclude:
  - README.md
